import { Logo } from "@/components";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tbm</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-[40rem] flex-col items-center justify-center ">
        TEXT BASED MINING OF DIGITAL EVIDENCES ON INSTAGRAM
        <Logo dot_styles="w-2 h-2 bg-c_yellow" />
      </main>
    </>
  );
};

export default Home;
